2020-05-30 11:14:27,222 ERROR: Exception on /user/jt [GET] [in /home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jin/dashboard/app/routes.py", line 77, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/jin/dashboard/app/templates/user.html", line 14, in template
    <p><a href="{{ url_for('follow'), username=user.username }}">Follow</a></p>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2020-05-30 11:14:29,940 ERROR: Exception on /user/jt [GET] [in /home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jin/dashboard/app/routes.py", line 77, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/jin/dashboard/app/templates/user.html", line 14, in template
    <p><a href="{{ url_for('follow'), username=user.username }}">Follow</a></p>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2020-05-30 11:15:41,988 ERROR: Exception on /user/jt [GET] [in /home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jin/dashboard/app/routes.py", line 77, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/jin/dashboard/app/templates/user.html", line 14, in template
    <p><a href="{{ url_for('follow'), username=user.username }}">Follow</a></p>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
