2020-05-30 11:18:58,398 ERROR: Exception on /user/jt [GET] [in /home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jin/dashboard/app/routes.py", line 77, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/jin/dashboard/app/templates/user.html", line 17, in template
    {% else %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'else'. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.
2020-05-30 11:19:47,313 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 11:19:49,189 ERROR: Exception on /user/jt [GET] [in /home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jin/dashboard/app/routes.py", line 77, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/jin/dashboard/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jin/dashboard/app/templates/base.html", line 28, in top-level template code
    {% block content %}{% endblock %}
  File "/home/jin/dashboard/app/templates/user.html", line 10, in block "content"
    <p>{{ user.folowers.count() }} followers, {{ user.followed.count() }} following.</p>
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'folowers'
2020-05-30 11:20:24,781 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 11:53:33,951 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 12:07:01,430 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 12:07:20,278 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 12:08:07,105 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 12:32:40,622 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 12:32:44,655 ERROR: Exception on /index [GET] [in /home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jin/miniconda/envs/webserver/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jin/dashboard/app/routes.py", line 28, in index
    page = requests.args.get('page', 1, type=int)
NameError: name 'requests' is not defined
2020-05-30 12:33:37,613 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 12:48:14,601 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 12:54:28,552 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 12:56:35,117 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
2020-05-30 13:03:09,973 INFO: Dashboard Startup [in /home/jin/dashboard/app/__init__.py:43]
